apiVersion: v2
name: hqv85942-ea-ioc-01
description: |
  An example IOC with a simulated area detector camera

type: application

# chart and app version - these are updated automatically by CI
version: 0.0.0-b0
appVersion: 0.0.0-b0

dependencies:
  - name: beamline-chart
    version: "1.0.0"
    repository: file://../../beamline-chart
    import-values:
      - beamline_defaults

  - name: helm-ioc-lib
    version: "1.8.1"
    repository: oci://ghcr.io/epics-containers
    import-values:
      - defaults

  # uncomment this to work with a local version of the helm library (comment above)
  # - name: helm-ioc-lib
  #   version: "1.0.0-b1"
  #   repository: file://../../../helm-ioc-lib
  #   import-values:
  #     - defaults
